version: '3'

services:

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=microservices
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./data/mysql:/data/mysql
    networks:
      - car-network


  cars:
    image: cars
    container_name: cars
    ports:
      - 8080:8080
    networks:
      - car-network
    # Necessary for connecting to MySQL inside a docker container
    external_links:
      - mysql:mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  used-cars:
    image: used-cars
    container_name: used-cars
    ports:
      - 9090:9090
    networks:
      - car-network
    # Necessary for connecting to MySQL inside a docker container
    external_links:
      - mysql:mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  car-network:


